site_name: MindNLP Docs
repo_url: https://github.com/mindspore-lab/mindnlp
repo_name: mindspore-lab/mindnlp
copyright: Copyright &copy; 2022 - 2024 MindSpore Lab and CQU NLP Team.

nav:
  - Home: index.md
  - Tutorials:
      - Quick Start: tutorials/quick_start.md
      - Data Preprocess: tutorials/data_preprocess.md
      - Use Trainer: tutorials/use_trainer.md
      - PEFT: tutorials/peft.md
      - Use Mirror: tutorials/use_mirror.md
  - Supported Models: supported_models.md
  - How-To Contribute:  contribute.md
  - API Reference:
      - Accelerate: api/accelerate.md
      - Data: api/data.md
      - Dataset: 
          - api/dataset/index.md
          - load_dataset: api/dataset/load_dataset.md
          - BaseMapFunction: api/dataset/BaseMapFunction.md
          - transforms: api/dataset/transforms.md

      - Engine:
          - train_args:
              base: api/engine/train_args/base.md
              seq2seq: api/engine/train_args/seq2seq.md
          - trainer:
              base: api/engine/trainer/base.md
              default_func: api/engine/trainer/default_func.md
          - callbacks: api/engine/callbacks.md
          - export: api/engine/export.md
          - utils: api/engine/utils.md

      - Modules: api/modules.md
      - Parallel: api/parallel.md
      - PEFT:
          - api/peft/index.md
          - tuners:
              AdaLoRA: api/peft/tuners/adalora.md
              Adaption_Prompt: api/peft/tuners/adaption_prompt.md
              IA3: api/peft/tuners/ia3.md
              LoKr: api/peft/tuners/lokr.md
              LoRA: api/peft/tuners/lora.md
              Prompt tuning: api/peft/tuners/prompt_tuning.md
          - utils:
              - merge_utils: api/peft/utils/merge_utils.md
          - config: api/peft/config.md
          - mapping: api/peft/mapping.md
          - peft_model: api/peft/peft_model.md

      - Sentence: api/sentence.md
      - Transformers:
          - api/transformers/index.md
          - generation:
              - api/transforemrs/generation/index.md
              - beam_constraints: api/transformers/generation/beam_constraints.md
              - beam_search: api/transformers/generation/beam_search.md
              - logits_process: api/transformers/generation/logits_process.md
              - stopping_criteria: api/transformers/generation/stopping_criteria.md
              - streamers: api/transformers/generation/streamers.md
              - utils: api/transformers/generation/utils.md
          - models:
              - api/transformers/models/index.md
              - albert: api/transformers/models/albert.md
              - align: api/transformers/models/align.md
              - altclip: api/transformers/models/altclip.md
              - audio_spectrogram_transformer: api/transformers/models/audio_spectrogram_transformer.md
              - auto: api/transformers/models/auto.md
              - autoformer: api/transformers/models/autoformer.md
              - baichuan: api/transformers/models/baichuan.md
              - bark: api/transformers/models/bark.md
              - bart: api/transformers/models/bart.md
              - barthez: api/transformers/models/barthez.md
              - bartpho: api/transformers/models/bartpho.md
              - beit: api/transformers/models/beit.md
              - bert: api/transformers/models/bert.md
              - bert_generation: api/transformers/models/bert_generation.md
              - bert_japanese: api/transformers/models/bert_japanese.md
              - bertweet: api/transformers/models/bertweet.md
              - bge_m3: api/transformers/models/bge_m3.md
              - big_bird: api/transformers/models/big_bird.md
              - bigbird_pegasus: api/transformers/models/bigbird_pegasus.md
              - biogpt: api/transformers/models/biogpt.md
              - bit: api/transformers/models/bit.md
              - blenderbot: api/transformers/models/blenderbot.md
              - blenderbot_small: api/transformers/models/blenderbot_small.md
              - blip: api/transformers/models/blip.md
              - blip_2: api/transformers/models/blip_2.md
              - bloom: api/transformers/models/bloom.md
              - bridgetower: api/transformers/models/bridgetower.md
              - bros: api/transformers/models/bros.md
              - byt5: api/transformers/models/byt5.md
              - camembert: api/transformers/models/camembert.md
              - canine: api/transformers/models/canine.md
              - chatglm: api/transformers/models/chatglm.md
              - chatglm2: api/transformers/models/chatglm2.md
              - chatglm3: api/transformers/models/chatglm3.md
              - clip: api/transformers/models/clip.md
              - codegen: api/transformers/models/codegen.md
              - cogvlm: api/transformers/models/cogvlm.md
              - cohere: api/transformers/models/cohere.md
              - convbert: api/transformers/models/convbert.md
              - convnext: api/transformers/models/convnext.md
              - cpm: api/transformers/models/cpm.md
              - cpmant: api/transformers/models/cpmant.md
              - cpmbee: api/transformers/models/cpmbee.md
              - ctrl: api/transformers/models/ctrl.md
              - cvt: api/transformers/models/cvt.md
              - data2vec: api/transformers/models/data2vec.md
              - deberta: api/transformers/models/deberta.md
              - deberta_v2: api/transformers/models/deberta_v2.md
              - decision_transformer: api/transformers/models/decision_transformer.md
              - distilbert: api/transformers/models/distilbert.md
              - efficientformer: api/transformers/models/efficientformer.md
              - efficientnet: api/transformers/models/efficientnet.md
              - electra: api/transformers/models/electra.md
              - encodec: api/transformers/models/encodec.md
              - ernie: api/transformers/models/ernie.md
              - ernie_m: api/transformers/models/ernie_m.md
              - esm: api/transformers/models/esm.md
              - falcon: api/transformers/models/falcon.md
              - flava: api/transformers/models/flava.md
              - funnel: api/transformers/models/funnel.md
              - gemma: api/transformers/models/gemma.md
              - git: api/transformers/models/git.md
              - gpt: api/transformers/models/gpt.md
              - gpt2: api/transformers/models/gpt2.md
              - gpt_bigcode: api/transformers/models/gpt_bigcode.md
              - gpt_neo: api/transformers/models/gpt_neo.md
              - gpt_neox: api/transformers/models/gpt_neox.md
              - gpt_neox_japanese: api/transformers/models/gpt_neox_japanese.md
              - gpt_pangu: api/transformers/models/gpt_pangu.md
              - gptj: api/transformers/models/gptj.md
              - graphormer: api/transformers/models/graphormer.md
              - groupvit: api/transformers/models/groupvit.md
              - hubert: api/transformers/models/hubert.md
              - imagegpt: api/transformers/models/imagegpt.md
              - internlm: api/transformers/models/internlm.md
              - jamba: api/transformers/models/jamba.md
              - jetmoe: api/transformers/models/jetmoe.md
              - layoutlm: api/transformers/models/layoutlm.md
              - layoutlmv2: api/transformers/models/layoutlmv2.md
              - led: api/transformers/models/led.md
              - llama: api/transformers/models/llama.md
              - llava: api/transformers/models/llava.md
              - llava_next: api/transformers/models/llava_next.md
              - longformer: api/transformers/models/longformer.md
              - longt5: api/transformers/models/longt5.md
              - luke: api/transformers/models/luke.md
              - mamba: api/transformers/models/mamba.md
              - marian: api/transformers/models/marian.md
              - maskformer: api/transformers/models/maskformer.md
              - mbart: api/transformers/models/mbart.md
              - megatron_bert: api/transformers/models/megatron_bert.md
              - megatron_gpt2: api/transformers/models/megatron_gpt2.md
              - minicpm: api/transformers/models/minicpm.md
              - minigpt4: api/transformers/models/minigpt4.md
              - mistral: api/transformers/models/mistral.md
              - mixtral: api/transformers/models/mixtral.md
              - mobilebert: api/transformers/models/mobilebert.md
              - mobilevit: api/transformers/models/mobilevit.md
              - moss: api/transformers/models/moss.md
              - mpnet: api/transformers/models/mpnet.md
              - mpt: api/transformers/models/mpt.md
              - mt5: api/transformers/models/mt5.md
              - musicgen: api/transformers/models/musicgen.md
              - musicgen_melody: api/transformers/models/musicgen_melody.md
              - mvp: api/transformers/models/mvp.md
              - nezha: api/transformers/models/nezha.md
              - nystromformer: api/transformers/models/nystromformer.md
              - olmo: api/transformers/models/olmo.md
              - openelm: api/transformers/models/openelm.md
              - opt: api/transformers/models/opt.md
              - owlvit: api/transformers/models/owlvit.md
              - pegasus: api/transformers/models/pegasus.md
              - phi: api/transformers/models/phi.md
              - phi3: api/transformers/models/phi3.md
              - poolformer: api/transformers/models/poolformer.md
              - pop2piano: api/transformers/models/pop2piano.md
              - qwen2: api/transformers/models/qwen2.md
              - qwen2_moe: api/transformers/models/qwen2_moe.md
              - reformer: api/transformers/models/reformer.md
              - regnet: api/transformers/models/regnet.md
              - rembert: api/transformers/models/rembert.md
              - resnet: api/transformers/models/resnet.md
              - roberta: api/transformers/models/roberta.md
              - roc_bert: api/transformers/models/roc_bert.md
              - rwkv: api/transformers/models/rwkv.md
              - sam: api/transformers/models/sam.md
              - seamless_m4t: api/transformers/models/seamless_m4t.md
              - seamless_m4t_v2: api/transformers/models/seamless_m4t_v2.md
              - segformer: api/transformers/models/segformer.md
              - seggpt: api/transformers/models/seggpt.md
              - speech_encoder_decoder: api/transformers/models/speech_encoder_decoder.md
              - speech_to_text: api/transformers/models/speech_to_text.md
              - squeezebert: api/transformers/models/squeezebert.md
              - stablelm: api/transformers/models/stablelm.md
              - starcoder2: api/transformers/models/starcoder2.md
              - swiftformer: api/transformers/models/swiftformer.md
              - switch_transformers: api/transformers/models/switch_transformers.md
              - t5: api/transformers/models/t5.md
              - table_transformer: api/transformers/models/table_transformer.md
              - timesformer: api/transformers/models/timesformer.md
              - tinybert: api/transformers/models/tinybert.md
              - transformer: api/transformers/models/transformer.md
              - van: api/transformers/models/van.md
              - vipllava: api/transformers/models/vipllava.md
              - vision_text_dual_encoder: api/transformers/models/vision_text_dual_encoder.md
              - visual_bert: api/transformers/models/visual_bert.md
              - vit: api/transformers/models/vit.md
              - wav2vec2: api/transformers/models/wav2vec2.md
              - wav2vec2_conformer: api/transformers/models/wav2vec2_conformer.md
              - wav2vec2_with_lm: api/transformers/models/wav2vec2_with_lm.md
              - wavlm: api/transformers/models/wavlm.md
              - whisper: api/transformers/models/whisper.md
              - x_clip: api/transformers/models/x_clip.md
              - xlm: api/transformers/models/xlm.md
              - xlm_roberta: api/transformers/models/xlm_roberta.md
              - xlm_roberta_xl: api/transformers/models/xlm_roberta_xl.md
              - xlnet: api/transformers/models/xlnet.md
          - pipeline:
              - api/transforemrs/pipeline/index.md
              - automatic_speech_recognition: api/transformers/pipeline/automatic_speech_recognition.md
              - base: api/transformers/pipeline/base.md
              - document_question_answering: api/transformers/pipeline/document_question_answering.md
              - fill_mask: api/transformers/pipeline/fill_mask.md
              - pipeline: api/transformers/pipeline/pipeline.md
              - question_answering: api/transformers/pipeline/question_answering.md
              - text2text_generation: api/transformers/pipeline/text2text_generation.md
              - text_classification: api/transformers/pipeline/text_classification.md
              - text_generation: api/transformers/pipeline/text_generation.md
              - zero_shot_classification: api/transformers/pipeline/zero_shot_classification.md
          - configuration_utils: api/transformers/configuration_utils.md
          - modeling_utils: api/transformers/modeling_utils.md
          - tokenization_utils: api/transformers/tokenization_utils.md
          - tokenization_utils_base: api/transformers/tokenization_utils_base.md
          - tokenization_utils_fast: api/transformers/tokenization_utils_fast.md

      - TRL: api/trl.md
      - Utils: api/utils.md
  - Notes:
      - Change Log: notes/changelog.md
      - Code of Conduct: notes/code_of_conduct.md
      - FAQ: notes/faq.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    # - navigation.instant  # see https://github.com/ultrabug/mkdocs-static-i18n/issues/62
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.path
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.action.view
    - content.action.edit
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotations
  favicon: assets/favicon.ico
  icon:
    logo: logo

markdown_extensions:
  # Officially Supported Extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - sane_lists
  - tables
  - toc:
      permalink: true
  - wikilinks
  # Third Party Extensions(Bundles, PyMdown Extensions)
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # Headings
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: true
            # Members
            show_submodules: false
            # Docstrings
            docstring_section_style: spacy
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
        - locale: zh
          default: false
          name: 中文
          nav_translations:
            Home: 主页
            Tutorials: 教程
            Supported Models: 模型列表
            Notes: 说明
            How-To Contribute: 代码贡献
            API Reference: API文档
            Change Log: 更新日志
            Code of Conduct: 行为准则
            FAQ: 常见问题

extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:lvyufeng@cqu.edu.cn
    - icon: fontawesome/brands/github
      link: https://github.com/mindspore-lab/mindnlp
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/lu-yu-feng-46-1
